# -*- coding: utf-8 -*-
"""EDGE - Calcium demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhdkHCeHoOg2z0FTgnPlPfIasmxYhcqr
"""

# !wget -O striatum.mp4 https://elifesciences.org/download/aHR0cHM6Ly9zdGF0aWMtbW92aWUtdXNhLmdsZW5jb2Vzb2Z0d2FyZS5jb20vbXA0LzEwLjc1NTQvNTcwLzg3NDc0MWZjMDM4ZDAwNTdjOTM1Y2UwMDMzNGM4MzRlMWM0YzYxMzYvZWxpZmUtMjg3MjgtdmlkZW8xLm1wNA--/elife-28728-video1.mp4?_hash=6uFTO7JVkkiKMNsF%2FPJbqziwgOnrRD0FQ%2BOJJ89B0Pk%3D
!wget -O striatum.mp4 https://static-movie-usa.glencoesoftware.com/mp4/10.7554/570/874741fc038d0057c935ce00334c834e1c4c6136/elife-28728-video1.mp4

!pip install sleap-io

import sleap_io as sio
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tqdm import tqdm

video = sio.load_video("striatum.mp4")
video.shape

frames = video[::100]
frames.shape

plt.imshow(frames[0])

bg = np.median(frames, axis=0).astype("float32")

plt.imshow(bg)

fg = frames - bg
fg_mu = fg.mean(axis=0)
fg_std = fg.std(axis=0)
fg = (fg - fg_mu) / fg_std

fg_mu.shape, fg_mu.dtype, fg_std.shape, fg_std.dtype

plt.imshow(np.abs(fg).max(axis=0))
plt.colorbar()

plt.imshow(fg[0])
plt.colorbar()

plt.imshow(fg[0], vmin=-3, vmax=3)
plt.colorbar()

cx, cy = 243, 349
roi = np.array([
    [cx - 10, cy - 10],  # top-left
    [cx + 10, cy - 10],  # top-right
    [cx + 10, cy + 10],  # bottom-right
    [cx - 10, cy + 10],  # bottom-left
])


plt.figure()
plt.imshow(fg[0], vmin=-3, vmax=3)
plt.colorbar()

plt.plot(roi[[0, 1, 2, 3, 0], 0], roi[[0, 1, 2, 3, 0], 1], "r-")

cx, cy = 243, 349
roi = np.array([
    [cx - 10, cy - 10],  # top-left
    [cx + 10, cy - 10],  # top-right
    [cx + 10, cy + 10],  # bottom-right
    [cx - 10, cy + 10],  # bottom-left
])

x0, x1 = roi[:, 0].min(), roi[:, 0].max()
y0, y1 = roi[:, 1].min(), roi[:, 1].max()

roi_frames = fg[:, y0:y1, x0:x1]
roi_frames.shape

# @title  { run: "auto" }
t = 77 # @param {type:"slider", min:0, max:89, step:1}

plt.figure(figsize=(2, 2))
plt.imshow(roi_frames[t])

roi_frames = []
for t in tqdm(range(len(video))):
    img = video[t]
    img = img - bg
    img = (img - fg_mu) / fg_std
    roi_img = img[y0:y1, x0:x1]
    roi_frames.append(roi_img)

roi_frames = np.stack(roi_frames, axis=0)
roi_frames.shape

# @title  { run: "auto" }
t = 1761 # @param {type:"slider", min:0, max:8998, step:1}

plt.figure(figsize=(2, 2))
plt.imshow(roi_frames[t])

trace = roi_frames.mean(axis=(1, 2, 3))
trace.shape

plt.figure(figsize=(10, 2))
plt.plot(trace)

cx, cy = 154, 338
roi = np.array([
    [cx - 10, cy - 10],  # top-left
    [cx + 10, cy - 10],  # top-right
    [cx + 10, cy + 10],  # bottom-right
    [cx - 10, cy + 10],  # bottom-left
])


plt.figure()
plt.imshow(fg[0], vmin=-3, vmax=3)
plt.colorbar()

plt.plot(roi[[0, 1, 2, 3, 0], 0], roi[[0, 1, 2, 3, 0], 1], "r-")

cx, cy = 154, 338
roi = np.array([
    [cx - 10, cy - 10],  # top-left
    [cx + 10, cy - 10],  # top-right
    [cx + 10, cy + 10],  # bottom-right
    [cx - 10, cy + 10],  # bottom-left
])

x0, x1 = roi[:, 0].min(), roi[:, 0].max()
y0, y1 = roi[:, 1].min(), roi[:, 1].max()


roi_frames = []
for t in tqdm(range(len(video))):
    img = video[t]
    img = img - bg
    img = (img - fg_mu) / fg_std
    roi_img = img[y0:y1, x0:x1]
    roi_frames.append(roi_img)

roi_frames = np.stack(roi_frames, axis=0)
roi_frames.shape

# @title  { run: "auto" }
t = 0 # @param {type:"slider", min:0, max:8998, step:1}

plt.figure(figsize=(2, 2))
plt.imshow(roi_frames[t])

plt.figure(figsize=(3, 2))
plt.imshow(np.abs(roi_frames).max(axis=0))
plt.colorbar()

trace = roi_frames.mean(axis=(1, 2, 3))

plt.figure(figsize=(10, 2))
plt.plot(trace)