# -*- coding: utf-8 -*-
"""EDGE - Neural signals of social isolation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHi6j34edcKM-X2gYmyHYytb9zCTPEIn

# EDGE - Neural signals of social isolation

## Setup
"""

!gdown --fuzzy https://drive.google.com/file/d/1Mh8oGKNyKpT5WS0Wu92SULFFanvqmSMf/view?usp=sharing
!gdown --fuzzy https://drive.google.com/file/d/1POpRqpA_QaWfZhxswQvLSs9uBnnHrmhZ/view?usp=sharing
!gdown --fuzzy https://drive.google.com/file/d/1UthpsskvkHbKKDsbQjUxyVN4Xkd-ZJuN/view?usp=sharing

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import h5py
import scipy.interpolate

"""## Load data"""

entrances = pd.read_excel("SI3_2022_Entrance_Frames.xlsx")
n_sessions = len(entrances)

behavior_fps = 25
session_keys = ["is_ag_sniffed", "is_ag_sniffing", "is_of_sniffed", "is_of_sniffing", "is_social", "is_social_receiver", "is_social_sender", "is_touched", "is_touching"]
behavior = []
with h5py.File("social_bouts.00.h5", "r") as f:
    for session_ind in range(n_sessions):
        session_data = {}
        for key in session_keys:
            session_data[key] = f[f"session_{session_ind}"][key][:]
        behavior.append(session_data)

imaging_fps = 30
imaging = []
with h5py.File("calcium.00.h5", "r") as f:
    for session_ind in range(n_sessions):
        imaging.append(f[f"session_{session_ind}"]["C"][:])

"""## EDA"""

entrances

len(behavior), len(imaging)

behavior[0].keys(), behavior[0]["is_social"].shape

imaging[0].shape

session_ind = 6

neurons = imaging[session_ind]
is_social = behavior[session_ind]["is_social_sender"]
condition = entrances["Isolation Length"].iloc[session_ind]
entry_frame = entrances["Int_Entry"].iloc[session_ind]

neurons.shape, is_social.shape, condition, entry_frame

"""### Interpolation sidebar"""

x = np.arange(0, 10)
y = x ** 2

plt.figure(figsize=(4, 2))
plt.plot(x, y, ".-")

x = np.arange(0, 10)
y = x ** 2

x2 = np.arange(0, 10, 0.5)
y2 = np.interp(x2, x, y)

plt.figure(figsize=(4, 2), dpi=200)
plt.plot(x, y, ".-", ms=20)
plt.plot(x2, y2, "x")

"""### Back to EDA"""

session_ind = 6

# Grab the session data
neurons = imaging[session_ind]
is_social = behavior[session_ind]["is_social_sender"]
condition = entrances["Isolation Length"].iloc[session_ind]
entry_frame = entrances["Int_Entry"].iloc[session_ind]

# Interpolate to resample to behavior sampling rate
neurons = scipy.interpolate.interp1d(
    x=np.linspace(0, 1, num=neurons.shape[0]),
    y=neurons,
    axis=0,
)(np.linspace(0, 1, num=len(is_social)))

# Z-score
neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

# Crop to first three mins after intruder entry
t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
neurons = neurons[t0:t1]
is_social = is_social[t0:t1]

neurons.shape, is_social.shape, condition

plt.figure(figsize=(9, 4))
plt.imshow(neurons.T, aspect="auto", interpolation="nearest")
plt.colorbar()

neuron_ind = 15

bins = np.linspace(-5, 5, num=100)
plt.figure(figsize=(9, 4))
plt.hist(neurons[~is_social, neuron_ind], bins=bins, density=True, alpha=0.5, label="Non-social")
plt.hist(neurons[is_social, neuron_ind], bins=bins, density=True, alpha=0.5, label="Social")
plt.legend()
plt.xlabel("Activity (z-score)")
plt.ylabel("PDF")

"""## Sandbox"""

social_activity = np.abs(neurons[is_social]).mean(axis=0)
non_social_activity = np.abs(neurons[~is_social]).mean(axis=0)
ratio = social_activity / non_social_activity

plt.figure(figsize=(4, 3))
plt.hist(ratio)

social_activity = np.abs(neurons[is_social]).mean(axis=0)
non_social_activity = np.abs(neurons[~is_social]).mean(axis=0)
ratio = social_activity / non_social_activity

is_social_neuron = ratio > 1.5
print(is_social_neuron.sum())

df = []

for session_ind in range(n_sessions):

    # Grab the session data
    neurons = imaging[session_ind]
    is_social = behavior[session_ind]["is_social_sender"]
    condition = entrances["Isolation Length"].iloc[session_ind]
    entry_frame = entrances["Int_Entry"].iloc[session_ind]

    # Interpolate to resample to behavior sampling rate
    neurons = scipy.interpolate.interp1d(
        x=np.linspace(0, 1, num=neurons.shape[0]),
        y=neurons,
        axis=0,
    )(np.linspace(0, 1, num=len(is_social)))

    # Z-score
    neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

    # Crop to first three mins after intruder entry
    t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
    neurons = neurons[t0:t1]
    is_social = is_social[t0:t1]

    # Find social neurons
    social_activity = np.abs(neurons[is_social]).mean(axis=0)
    non_social_activity = np.abs(neurons[~is_social]).mean(axis=0)
    ratio = social_activity / non_social_activity

    is_social_neuron = ratio > 1.5
    n_social_neurons = is_social_neuron.sum()

    df.append({
        "session_ind": session_ind,
        "condition": "control" if "GH" in condition else condition,
        "n_social_neurons": n_social_neurons
    })

df = pd.DataFrame(df)
df.groupby("condition").mean().drop(columns="session_ind")

df = []

for session_ind in range(n_sessions):

    # Grab the session data
    neurons = imaging[session_ind]
    is_social = behavior[session_ind]["is_social_sender"]
    condition = entrances["Isolation Length"].iloc[session_ind]
    entry_frame = entrances["Int_Entry"].iloc[session_ind]

    # Interpolate to resample to behavior sampling rate
    neurons = scipy.interpolate.interp1d(
        x=np.linspace(0, 1, num=neurons.shape[0]),
        y=neurons,
        axis=0,
    )(np.linspace(0, 1, num=len(is_social)))

    # Z-score
    neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

    # Crop to first three mins after intruder entry
    t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
    neurons = neurons[t0:t1]
    is_social = is_social[t0:t1]

    # Find social neurons
    social_activity = neurons[is_social].mean(axis=0)
    non_social_activity = neurons[~is_social].mean(axis=0)
    delta = social_activity - non_social_activity

    is_social_neuron = (delta > 0.5) | (delta < -0.5)
    n_social_neurons = is_social_neuron.sum()

    df.append({
        "session_ind": session_ind,
        "condition": "control" if "GH" in condition else condition,
        "n_social_neurons": n_social_neurons
    })

df = pd.DataFrame(df)
df.groupby("condition").mean().drop(columns="session_ind")

df = []

for session_ind in range(n_sessions):

    # Grab the session data
    neurons = imaging[session_ind]
    is_social = behavior[session_ind]["is_social_sender"]
    condition = entrances["Isolation Length"].iloc[session_ind]
    entry_frame = entrances["Int_Entry"].iloc[session_ind]

    # Interpolate to resample to behavior sampling rate
    neurons = scipy.interpolate.interp1d(
        x=np.linspace(0, 1, num=neurons.shape[0]),
        y=neurons,
        axis=0,
    )(np.linspace(0, 1, num=len(is_social)))

    # Z-score
    neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

    # Crop to first three mins after intruder entry
    t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
    neurons = neurons[t0:t1]
    is_social = is_social[t0:t1]

    # Find social neurons
    hi_thresh = np.percentile(neurons, 95, axis=0, keepdims=True)
    lo_thresh = np.percentile(neurons, 5, axis=0, keepdims=True)
    is_hi = neurons > hi_thresh
    is_lo = neurons < lo_thresh
    is_active = is_hi | is_lo
    is_responsive = is_active & is_social.reshape(-1, 1)
    is_social_neuron = is_responsive.mean(axis=0) > 0.01
    n_social_neurons = is_social_neuron.sum()

    df.append({
        "session_ind": session_ind,
        "condition": "control" if "GH" in condition else condition,
        "n_social_neurons": n_social_neurons
    })

df = pd.DataFrame(df)
df.groupby("condition").mean().drop(columns="session_ind").loc[["control", "24hr", "7d"]]

df = []

for session_ind in range(n_sessions):

    # Grab the session data
    neurons = imaging[session_ind]
    is_social = behavior[session_ind]["is_social_sender"]
    condition = entrances["Isolation Length"].iloc[session_ind]
    entry_frame = entrances["Int_Entry"].iloc[session_ind]

    # Interpolate to resample to behavior sampling rate
    neurons = scipy.interpolate.interp1d(
        x=np.linspace(0, 1, num=neurons.shape[0]),
        y=neurons,
        axis=0,
    )(np.linspace(0, 1, num=len(is_social)))

    # Crop to first three mins after intruder entry
    t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
    neurons = neurons[t0:t1]
    is_social = is_social[t0:t1]

    # Z-score
    neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

    # Find social neurons
    social_activity = neurons[is_social].mean(axis=0)
    non_social_activity = neurons[~is_social].mean(axis=0)
    delta = social_activity - non_social_activity

    is_social_neuron = (delta > 0.5) | (delta < -0.5)
    n_social_neurons = is_social_neuron.sum()

    df.append({
        "session_ind": session_ind,
        "condition": "control" if "GH" in condition else condition,
        "n_social_neurons": n_social_neurons
    })

df = pd.DataFrame(df)
df.groupby("condition").mean().drop(columns="session_ind")

df = []

for session_ind in range(n_sessions):

    # Grab the session data
    neurons = imaging[session_ind]
    is_social = behavior[session_ind]["is_social_sender"]
    condition = entrances["Isolation Length"].iloc[session_ind]
    entry_frame = entrances["Int_Entry"].iloc[session_ind]

    # Interpolate to resample to behavior sampling rate
    neurons = scipy.interpolate.interp1d(
        x=np.linspace(0, 1, num=neurons.shape[0]),
        y=neurons,
        axis=0,
    )(np.linspace(0, 1, num=len(is_social)))

    # Crop to first three mins after intruder entry
    t0, t1 = entry_frame, int(entry_frame + 3 * 60 * behavior_fps)
    neurons = neurons[t0:t1]
    is_social = is_social[t0:t1]

    # Z-score
    neurons = (neurons - neurons.mean(axis=0, keepdims=True)) / neurons.std(axis=0, keepdims=True)

    # hi_thresh = np.percentile(neurons, 95, axis=0, keepdims=True)
    # lo_thresh = np.percentile(neurons, 5, axis=0, keepdims=True)


    # Find social neurons
    hi_thresh = np.percentile(neurons, 95, axis=0, keepdims=True)
    lo_thresh = np.percentile(neurons, 5, axis=0, keepdims=True)
    is_hi = neurons > hi_thresh
    is_lo = neurons < lo_thresh
    is_active = is_hi | is_lo
    is_responsive = is_active & is_social.reshape(-1, 1)
    is_social_neuron = is_responsive.mean(axis=0) > 0.01
    n_social_neurons = is_social_neuron.sum()

    df.append({
        "session_ind": session_ind,
        "condition": "control" if "GH" in condition else condition,
        "n_social_neurons": n_social_neurons
    })

df = pd.DataFrame(df)
df.groupby("condition").mean().drop(columns="session_ind").loc[["control", "24hr", "7d"]]