# -*- coding: utf-8 -*-
"""EDGE - Demixed calcium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEZ13yr_5usvYLXFmTtTaepH7bVPeCU3

# EDGE - Demixed calcium

## Setup
"""

!gdown --fuzzy https://drive.google.com/file/d/1PYLeqT88IH_9JWNPwYaUC9WJVT2IqevL/view?usp=sharing

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import h5py

"""## EDA"""

with h5py.File("221007_4-0_D2_neuron_refined.h5", "r") as f:
    for key in f.keys():
        ds = f[key]
        print(f"{key:>9}: {ds.shape} ({ds.dtype})")

with h5py.File("221007_4-0_D2_neuron_refined.h5", "r") as f:
    A = f["A"][:]  # spatial coefficients
    C = f["C"][:]  # calcium activity
    Cn = f["Cn"][:]  # correlation image
    S = f["S"][:]  # deconvolved spikes (warning: not validated for 1p)
    Fs = f["Fs"][:].squeeze()  # sampling frequency (FPS)

n_neurons = A.shape[0]
n_frames = C.shape[0]
img_shape = Cn.shape

print("n_neurons:", n_neurons)
print("n_frames:", n_frames)
print("img_shape:", img_shape)
print("Fs:", Fs)

plt.figure(figsize=(6, 5))
plt.imshow(Cn)
plt.axis("off")
plt.colorbar()

# @title  { run: "auto" }
neuron_ind = 148 # @param {type:"slider", min:0, max:201, step:1}

a = A[neuron_ind]
a = a.reshape(img_shape)

plt.figure(figsize=(6, 5))
plt.imshow(a)
plt.axis("off")
plt.colorbar()

print(A.shape)
print(A.max(axis=1).shape)
print(A.max(axis=1, keepdims=True).shape)

# A_max = A.max(axis=0).reshape(img_shape)
A_max = A / A.max(axis=1, keepdims=True)
A_max = A_max.max(axis=0)
A_max = A_max.reshape(img_shape)

plt.figure(figsize=(6, 5))
plt.imshow(A_max)
plt.axis("off")
plt.colorbar()

neurons = C.T

plt.figure(figsize=(12, 5))
plt.imshow(neurons, aspect="auto")
plt.xlabel("Time (frames)")
plt.ylabel("Neuron")

neurons = C.T
neurons = (neurons - neurons.mean(axis=1, keepdims=True)) / neurons.std(axis=1, keepdims=True)

plt.figure(figsize=(12, 5))
plt.imshow(neurons, aspect="auto")
plt.xlabel("Time (frames)")
plt.ylabel("Neuron")
plt.colorbar()

df = pd.DataFrame(C[:, :50])
df = (df - df.min()) / (df.max() - df.min())

df_melted = df.reset_index().melt(id_vars="index", var_name="neuron", value_name="activity")
# df_melted["activity"] += df_melted["neuron"] * 0.8

plt.figure(figsize=(14, 7))
sns.lineplot(data=df_melted, x="index", y="activity", hue="neuron", lw=1, legend=False)
plt.xlabel("Time (frames)")
plt.ylabel("Neurons")
plt.xlim(0, n_frames)

df = pd.DataFrame(C[:, :50])
df = (df - df.min()) / (df.max() - df.min())

df_melted = df.reset_index().melt(id_vars="index", var_name="neuron", value_name="activity")
df_melted["activity"] += df_melted["neuron"] * 0.8

plt.figure(figsize=(14, 7))
sns.lineplot(data=df_melted, x="index", y="activity", hue="neuron", lw=1, legend=False)
plt.xlabel("Time (frames)")
plt.ylabel("Neurons")
plt.xlim(0, n_frames)

df.head()

df_melted.head()

entry_time = int(7488 * (30 / 25))
three_min = entry_time + (3 * 60 * 30)

entry_time, three_min

neurons = C.T
neurons = (neurons - neurons.mean(axis=1, keepdims=True)) / neurons.std(axis=1, keepdims=True)

plt.figure(figsize=(12, 5))
plt.imshow(neurons, aspect="auto")
plt.axvline(entry_time, color="g")
plt.axvline(three_min, color="r")
plt.xlabel("Time (frames)")
plt.ylabel("Neuron")
plt.colorbar()

neurons = C.T
neurons = (neurons - neurons.mean(axis=1, keepdims=True)) / neurons.std(axis=1, keepdims=True)

plt.figure(figsize=(7, 5))
plt.imshow(neurons, aspect="auto")
plt.xlim(entry_time, three_min)
plt.xlabel("Time (frames)")
plt.ylabel("Neuron")
plt.colorbar()

neurons = C.T
neurons = (neurons - neurons.mean(axis=1, keepdims=True)) / neurons.std(axis=1, keepdims=True)

neurons = neurons[:, entry_time:three_min]
neurons.shape

threshold = 5.0

first_hi_inds = np.argmax(neurons > threshold, axis=1)
sort_inds = np.argsort(first_hi_inds)[::-1]

plt.figure(figsize=(12, 5))
plt.imshow(neurons[sort_inds], aspect="auto", interpolation="nearest")
plt.xlabel("Time (frames)")
plt.ylabel("Neuron")
plt.colorbar()