# -*- coding: utf-8 -*-
"""EDGE - Find place cells and grid cells.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oOAXb2MIkq7yvOQPWGFLoJZBM81rUkT
"""

!wget -O HW1_RatData.zip https://www.dropbox.com/scl/fi/w6afx6u18tuo7xc439iq2/HW1_RatData.zip?rlkey=fj6dorj1udb45nc4i9j3j7mz6&st=yax6wk13&dl=0
!unzip HW1_RatData.zip

"""This is based on a [problem set](https://www.dropbox.com/scl/fi/xejrh07xru263yojapdg2/neu-457-homework1.pdf?rlkey=daukk0bljwzc9pnee5j3pw3d1&st=hoc9u405&dl=0) developed for NEU 457 at Princeton by Talmo Pereira, Andrew Leifer and David Tank."""

import numpy as np
from scipy.io import loadmat

mat_data = loadmat("20160609T194655.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

left.shape, left.dtype, right.shape, right.dtype, spikes.shape, spikes.dtype

left[:3]

right[:3]

spikes[:3]

is_spiking = spikes[:, 0] > 0
is_spiking

spike_inds = np.argwhere(is_spiking).squeeze()
spike_inds.shape

spike_inds[0]

left[136], right[136]

import matplotlib.pyplot as plt

plt.plot(left[:, 0], left[:, 1])

plt.scatter(left[:, 0], left[:, 1], c=np.arange(len(left)), alpha=0.5)

plt.figure()
plt.plot(left[:, 0])

plt.figure()
plt.plot(left[:, 1])

plt.figure(figsize=(12, 2), dpi=72)
plt.plot(left[:, 0], label="x")
plt.plot(left[:, 1], label="y")
plt.legend()
plt.xlabel("Time (frames)")
plt.ylabel("Position (pixels)")
plt.title("Left Eye Position")

plt.figure(figsize=(12, 2), dpi=200)
plt.plot(left[:, 0], label="x")
plt.plot(left[:, 1], label="y")
plt.legend()
plt.xlabel("Time (frames)")
plt.ylabel("Position (pixels)")
plt.title("Left Eye Position")

plt.figure(figsize=(12, 2), dpi=150)
plt.plot(right[:, 0], label="x")
plt.plot(right[:, 1], label="y")
plt.legend()
plt.xlabel("Time (frames)")
plt.ylabel("Position (pixels)")
plt.title("Right Eye Position")

plt.figure(figsize=(12, 2), dpi=150)
plt.plot(left[:, 0], label="left_x", lw=0.5, alpha=0.5)
plt.plot(left[:, 1], label="left_y", lw=0.5, alpha=0.5)
plt.plot(right[:, 0], label="right_x", lw=0.5, alpha=0.5)
plt.plot(right[:, 1], label="right_y", lw=0.5, alpha=0.5)
plt.legend()
plt.xlabel("Time (frames)")
plt.ylabel("Position (pixels)")
plt.title("Eye Positions")

plt.figure(figsize=(12, 2), dpi=150)
plt.plot(spikes[:, 0], lw=0.5, alpha=0.5)
plt.xlabel("Time (frames)")
plt.ylabel("Spike count")

plt.figure(figsize=(12, 2), dpi=150)
plt.plot(spikes[:, 0] > 0, lw=0.5, alpha=0.5)
plt.xlabel("Time (frames)")
plt.ylabel("Spike count")

spikes[:, 0].reshape(60748, 1).shape

spikes[:, 0].reshape(spikes.shape[0], 1).shape

spikes[:, 0].reshape(len(spikes), 1).shape

spikes[:, 0].reshape(-1, 1).shape

np.expand_dims(spikes[:, 0], axis=1).shape

plt.figure(figsize=(12, 1))
plt.imshow(spikes[:, 0].reshape(1, -1), aspect="auto", interpolation="nearest")
plt.colorbar();

plt.figure(figsize=(12, 1))
plt.imshow(spikes[:, 0].reshape(1, -1) > 0, aspect="auto", interpolation="nearest")

t = 0

left[t], right[t]

(left[t] + right[t]) / 2

(left[t, 0] + right[t, 0]) / 2, (left[t, 1] + right[t, 1]) / 2

ctr = (left + right) / 2
ctr.shape

n_frames = left.shape[0]
ctr = np.full((n_frames, 2), np.nan)
for t in range(n_frames):
    ctr[t, 0] = (left[t, 0] + right[t, 0]) / 2
    ctr[t, 1] = (left[t, 1] + right[t, 1]) / 2
ctr.shape

ctr = (left + right) / 2
ctr.shape

# Commented out IPython magic to ensure Python compatibility.
# %%time
# n_frames = left.shape[0]
# ctr = np.full((n_frames, 2), np.nan)
# for t in range(n_frames):
#     ctr[t, 0] = (left[t, 0] + right[t, 0]) / 2
#     ctr[t, 1] = (left[t, 1] + right[t, 1]) / 2
# ctr.shape

# Commented out IPython magic to ensure Python compatibility.
# %%time
# ctr = (left + right) / 2
# ctr.shape

plt.plot(ctr[:, 0], ctr[:, 1])

is_every_ten = np.arange(n_frames) % 10 == 0

plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_every_ten, 0], ctr[is_every_ten, 1], "r.")

# Parameters ("knobs")
neuron_ind = 1

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

# @title  { run: "auto", vertical-output: true }
# Parameters ("knobs")
neuron_ind = 0 # @param {type:"slider", min:0, max:14, step:1}

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

mat_data = loadmat("20160607T172746.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

ctr = (left + right) / 2

spikes.shape

# @title  { run: "auto", vertical-output: true }
# Parameters ("knobs")
neuron_ind = 5 # @param {type:"slider", min:0, max:5, step:1}

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

mat_data = loadmat("20160521T142946.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

ctr = (left + right) / 2

spikes.shape

# @title  { run: "auto", vertical-output: true }
# Parameters ("knobs")
neuron_ind = 3 # @param {type:"slider", min:0, max:4, step:1}

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

import seaborn as sns
import pandas as pd

spike_locs = []

for neuron_ind in range(spikes.shape[1]):
    spikes_neuron = spikes[:, neuron_ind]
    is_spiking = spikes_neuron > 0

    spike_inds = np.argwhere(is_spiking).squeeze()
    spike_locs.append(pd.DataFrame({
        "neuron": np.full(spike_inds.shape, neuron_ind),
        "x": ctr[spike_inds, 0],
        "y": ctr[spike_inds, 1]
    }))

spike_locs = pd.concat(spike_locs)
spike_locs

neuron_ind = 4

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.5)

mat_data = loadmat("20160607T172746.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

ctr = (left + right) / 2

spikes.shape

spike_locs = []

for neuron_ind in range(spikes.shape[1]):
    spikes_neuron = spikes[:, neuron_ind]
    is_spiking = spikes_neuron > 0

    spike_inds = np.argwhere(is_spiking).squeeze()
    spike_locs.append(pd.DataFrame({
        "neuron": np.full(spike_inds.shape, neuron_ind),
        "x": ctr[spike_inds, 0],
        "y": ctr[spike_inds, 1]
    }))

spike_locs = pd.concat(spike_locs)

# Parameters ("knobs")
neuron_ind = 5

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

neuron_ind = 5

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.2)
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.3)

neuron_ind = 5

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.3)
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.3)

mat_data = loadmat("20160521T142946.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

ctr = (left + right) / 2


spike_locs = []

for neuron_ind in range(spikes.shape[1]):
    spikes_neuron = spikes[:, neuron_ind]
    is_spiking = spikes_neuron > 0

    spike_inds = np.argwhere(is_spiking).squeeze()
    spike_locs.append(pd.DataFrame({
        "neuron": np.full(spike_inds.shape, neuron_ind),
        "x": ctr[spike_inds, 0],
        "y": ctr[spike_inds, 1]
    }))

spike_locs = pd.concat(spike_locs)

# Parameters ("knobs")
neuron_ind = 3

# Data processing
spikes_neuron = spikes[:, neuron_ind]
is_spiking = spikes_neuron > 0

# Plotting
plt.figure(figsize=(8, 8))
plt.plot(ctr[:, 0], ctr[:, 1])
plt.plot(ctr[is_spiking, 0], ctr[is_spiking, 1], "r.")

neuron_ind = 3

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.0)
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.3)

neuron_ind = 3

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.0)
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.3)

neuron_ind = 3

df = spike_locs[spike_locs["neuron"] == neuron_ind]

plt.figure(figsize=(6, 6))
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.0)
# sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=0.3)
sns.kdeplot(data=df, x="x", y="y", fill=True, bw_adjust=1.8)

mat_data = loadmat("20160609T194655.mat")
left = mat_data["left"]
right = mat_data["right"]
spikes = mat_data["spikes"]

# find centroid
ctr = (left + right) / 2
neuron_ind = 5

# data processing
x_positions = ctr[:, 0]
y_positions = ctr[:, 1]
spikes_neuron = spikes[:, neuron_ind]
# is_spiking = spikes_neuron > 0
firing_rates = spikes_neuron.astype(spikes_neuron.dtype)

is_valid = np.isfinite(x_positions) & np.isfinite(y_positions)
x_positions = x_positions[is_valid]
y_positions = y_positions[is_valid]
firing_rates = firing_rates[is_valid]

# plotting
hist, xbins, ybins = np.histogram2d(x_positions, y_positions, bins=20, weights=firing_rates, density=True)
plt.imshow(hist, interpolation='nearest', origin='lower', extent=[xbins[0], xbins[-1], ybins[0], ybins[-1]])
plt.colorbar()
plt.show()

x_positions, y_positions

np.isnan(x_positions).sum()