# -*- coding: utf-8 -*-
"""EDGE - Motion correction visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL9mE9kZ2nr_RX0W6N7-dEDReifEeowR
"""

!gdown --fuzzy https://drive.google.com/file/d/1cx7vG3w0FjxsWpMKSrV2XYFKV8kwa7Y7/view?usp=sharing

!pip install sleap-io

import numpy as np
import matplotlib.pyplot as plt
import sleap_io as sio

# Commented out IPython magic to ensure Python compatibility.
# %%time
# mov = sio.load_video("1-s2.0-S0165027017302753-mmc3.mp4")[:].squeeze()
# mov.shape

w = mov.shape[2] // 3
y0, y1 = w // 2, mov.shape[1] - w // 2

raw = mov[:, y0:y1, :w]
rigid = mov[:, y0:y1, w:(2 * w)]
pwr = mov[:, y0:y1, (2 * w):]

raw.shape, rigid.shape, pwr.shape

t = 0

plt.figure(figsize=(8, 3))
plt.subplot(1, 3, 1)
plt.imshow(raw[t], cmap="gray")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(rigid[t], cmap="gray")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(pwr[t], cmap="gray")
plt.axis("off")

plt.tight_layout(pad=0.8)

y = 80

raw_kymo = raw[:, y, :].squeeze()
rigid_kymo = rigid[:, y, :].squeeze()
pwr_kymo = pwr[:, y, :].squeeze()

raw_kymo.shape, rigid_kymo.shape, pwr_kymo.shape

plt.figure(figsize=(6, 6))
plt.subplot(1, 3, 1)
plt.imshow(raw_kymo, cmap="gray")
plt.axis("off")
plt.title("Raw")
plt.subplot(1, 3, 2)
plt.imshow(rigid_kymo, cmap="gray")
plt.axis("off")
plt.title("Rigid")
plt.subplot(1, 3, 3)
plt.imshow(pwr_kymo, cmap="gray")
plt.axis("off")
plt.title("PW-Rigid")

plt.tight_layout(pad=0.8)

t0, t1 = 350, 400


plt.figure(figsize=(6, 6))
plt.subplot(1, 3, 1)
plt.imshow(raw_kymo, cmap="gray")
plt.axis("off")
plt.title("Raw")
plt.axhline(y=t0, color="red", linewidth=1)
plt.axhline(y=t1, color="red", linewidth=1)
plt.subplot(1, 3, 2)
plt.imshow(rigid_kymo, cmap="gray")
plt.axis("off")
plt.title("Rigid")
plt.axhline(y=t0, color="red", linewidth=1)
plt.axhline(y=t1, color="red", linewidth=1)
plt.subplot(1, 3, 3)
plt.imshow(pwr_kymo, cmap="gray")
plt.axis("off")
plt.title("PW-Rigid")
plt.axhline(y=t0, color="red", linewidth=1)
plt.axhline(y=t1, color="red", linewidth=1)

plt.tight_layout(pad=0.8)

t0, t1 = 350, 400

plt.figure(figsize=(5, 3), dpi=150)
plt.subplot(1, 3, 1)
plt.imshow(raw_kymo, cmap="gray", aspect="auto", interpolation="nearest")
plt.axis("off")
plt.title("Raw")
plt.ylim([t0, t1])
plt.subplot(1, 3, 2)
plt.imshow(rigid_kymo, cmap="gray", aspect="auto", interpolation="nearest")
plt.axis("off")
plt.title("Rigid")
plt.ylim([t0, t1])
plt.subplot(1, 3, 3)
plt.imshow(pwr_kymo, cmap="gray", aspect="auto", interpolation="nearest")
plt.axis("off")
plt.title("PW-Rigid")
plt.ylim([t0, t1])

plt.tight_layout(pad=0.8)

# Parameters
y = 120

# Processing
raw_kymo = raw[:, y, :].squeeze()
rigid_kymo = rigid[:, y, :].squeeze()
pwr_kymo = pwr[:, y, :].squeeze()

# Plotting
plt.figure(figsize=(6, 6))
plt.subplot(1, 3, 1)
plt.imshow(raw_kymo, cmap="gray")
plt.axis("off")
plt.title("Raw")
plt.subplot(1, 3, 2)
plt.imshow(rigid_kymo, cmap="gray")
plt.axis("off")
plt.title("Rigid")
plt.subplot(1, 3, 3)
plt.imshow(pwr_kymo, cmap="gray")
plt.axis("off")
plt.title("PW-Rigid")

plt.tight_layout(pad=0.8)