# -*- coding: utf-8 -*-
"""EDGE - Analyzing social isolation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqRrS3MS1ASBeJjJCLOUbxqvP5VSOW1j

# EDGE - Analyzing social isolation

## Setup
"""

!gdown --fuzzy https://drive.google.com/file/d/1Mh8oGKNyKpT5WS0Wu92SULFFanvqmSMf/view?usp=sharing
!gdown --fuzzy https://drive.google.com/file/d/1POpRqpA_QaWfZhxswQvLSs9uBnnHrmhZ/view?usp=sharing

!ls -lah

"""## EDA"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import h5py

entrances = pd.read_excel("SI3_2022_Entrance_Frames.xlsx")
entrances

with h5py.File("social_bouts.00.h5", "r") as f:
    # List out top-level keys.
    print(f.keys())

    # List out keys inside of one of the groups.
    print(f["session_0"].keys())
    print()

    # Print out metadata about the session keys.
    for key in f["session_0"].keys():
        ds = f["session_0"][key]
        print(f"{key:>20}: {ds.shape} ({ds.dtype})")


# is_touched = sender_nose < threshold_distance to anywhere on the body
# is_social_receiver = is_touched | is_ag_sniffed | is_of_sniffed
# is_social_sender = is_touching | is_ag_sniffing | is_of_sniffing
# is_social = is_social_receiver | is_social_sender

n_sessions = len(entrances)

session_keys = ['is_ag_sniffed', 'is_ag_sniffing', 'is_of_sniffed', 'is_of_sniffing', 'is_social', 'is_social_receiver', 'is_social_sender', 'is_touched', 'is_touching']

social_bouts = []

with h5py.File("social_bouts.00.h5", "r") as f:
    for session_ind in range(n_sessions):
        session_data = {}
        for key in session_keys:
            session_data[key] = f[f"session_{session_ind}"][key][:]
        social_bouts.append(session_data)

len(social_bouts)

social_bouts[0].keys()

session_ind = 5

session_data = social_bouts[session_ind]

ethogram = np.stack(list(session_data.values()), axis=1).T
print(ethogram.shape)

plt.figure(figsize=(12, 5))
plt.imshow(ethogram, aspect="auto", interpolation="nearest")
plt.yticks(np.arange(len(session_keys)), labels=session_keys)
plt.xlabel("Time (frames)")

session_ind = 5

session_data = social_bouts[session_ind]

ethogram = np.stack(list(session_data.values()), axis=1)
print(ethogram.shape)

df = pd.DataFrame(ethogram, columns=session_keys)
df

entrances["Isolation Length"]